#!/bin/bash

# Run this from the repository root to enable all git hooks for this project.

# Exit build script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# If there's an existing symlink, remove it.
if [[ -L .git/hooks ]]
then
  rm .git/hooks
fi

# If it's a regular directory, remove all files.
if [[ -d .git/hooks ]]
then
  rm -rf .git/hooks
fi

ln -s -f ../dev-scripts/hooks .git/hooks
